language: scala

jdk:
  - openjdk8

matrix:
  include:
    - env: SCALA_VERSION=2.12.8 SPARK_VERSION=2.4.4

script:
  - sbt -Dscala.version=$SCALA_VERSION -Dspark.version=$SPARK_VERSION coverage test coverageReport
