dist: trusty

language: scala

python:
  - "3.6"
jdk:
  - openjdk8

matrix:
  include:
    - env: SCALA_VERSION=2.12.10 SPARK_VERSION=3.0.0

install:
  - pip install --user pyspark==$SPARK_VERSION
  - pip install --user -r python/requirements.txt
  - pip install --user -r python/requirements-test.txt

script:
  - sbt -Dscala.version=$SCALA_VERSION -Dspark.version=$SPARK_VERSION "set test in assembly := {}" assembly
  - sbt -Dscala.version=$SCALA_VERSION -Dspark.version=$SPARK_VERSION coverage test coverageReport
  - ./python/run-tests.sh

after_success:
  - codecov
