language: scala

jdk:
  - openjdk8

matrix:
  include:
    - env: SCALA_VERSION=2.12.8 SPARK_VERSION=2.4.4

install:
  - pip install --user pyspark==$SPARK_VERSION

script:
  - sbt -Dscala.version=$SCALA_VERSION -Dspark.version=$SPARK_VERSION coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
